language: node_js
node_js:
  - 0.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g ./src/front/package.json
  - ./src/front/scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - karma start ./src/front/config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - karma start ./src/front/config/karma-e2e.conf.js --reporters=dots --browsers=Firefox
